name: 'Terraform Deploy'

on:
  push:
    branches:
    - main
  pull_request:
 
jobs:
  terraform:
    uses: ./.github/workflows/template-terraform.yaml
    strategy:
      matrix:
        environment: ['development','production']
        platform_directory: ['core','logging','network']
      fail-fast: true
      max-parallel: 1
    with:
      environment: ${{ matrix.environment }}
      backend_tf_rg: thomasthorntoncloud
      backend_tf_sa: thomasthorntontfstate
      backend_tfstate_name: ${{ matrix.environment }}-tf-github${{ matrix.platform_directory }}
      tfstate_container: 90daysdevops-github-tf-at-scale-${{ matrix.environment }}
      platform_directory: ${{ matrix.platform_directory }}
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      DEPLOYMENT_SUBSCRIPTION_ID: ${{ secrets.DEPLOYMENT_SUBSCRIPTION_ID }}
      USER_TOKEN: ${{ secrets.USER_TOKEN }}
  terraform-ci:
    if: github.ref != 'refs/heads/main'
    uses: ./.github/workflows/template-terraform-ci.yaml